### ISSUE TITLE
How to set spec info using K8sReplicationController?

### ISSUE THREAD

**Issue by pigletfly** [mnubo/kubernetes-py#1]
I want to set or init some spec info,and found no api support this?such as cpu or memory limits.

**Comment by sebastienc** [comment]
Hi, these are set at the container level so something like:

    my_pod = K8sPod(config=my_cfg, name=name)
    my_pod.add_container(container=K8sContainer(name=name, image=full_image_name)
                           .add_port(container_port=container_port, host_port=host_port, name=port_name)
                           .set_limit_resources(cpu="100m", mem="1024M")
                           .set_liveness_probe(handler='httpGet', port=80, initial_delay_s=5)
                           .set_readiness_probe(handler='httpGet', port=80, initial_delay_s=5))
   my_pod.create()

This would limit to 0.1 CPU and 1024M of memory.

Does that answer your question?

**Comment by pigletfly** [comment]
Yes, K8sPod can handle detail spec.But if I want use ```K8sReplicationController``` to resize replicas and set some detail spec at the same time?Or can K8sPod attach to a K8sReplicationController?

**Comment by sebastienc** [comment]
Aaah I see, then you could set it at creation time this way:

my_rc = K8sReplicationController(config=my_cfg, name=rc_name, replicas=1)
my_rc.add_container(container=K8sContainer(name=name, image=full_image_name)
                       .add_port(container_port=container_port, host_port=host_port, name=port_name)
                       .set_limit_resources(cpu="100m", mem="1024M")
                       .set_liveness_probe(handler='httpGet', port=80, initial_delay_s=5)
                       .set_readiness_probe(handler='httpGet', port=80, initial_delay_s=5))

I haven't made an easy way to change something existing except if you happen to change the containers in the active definition and trigger a rolling restart.

**Comment by sebastienc** [comment]
Can we close this case?
