### ISSUE TITLE
Document supported Python versions in README, and PyPi

### ISSUE THREAD

**Issue by movermeyer** [mnubo/kubernetes-py#110]
When I am considering using a new Python library, perhaps the most important information I need is to be able to tell what versions of Python the library supports.

Typically I look for:

1. I look for PyPi badges at the top of the README.MD file. ([for an example, see pyhocon](https://github.com/chimpler/pyhocon))
2. A list of supported version in the README.MD more generally.
3. Version categories from the setup.py displayed in the PyPi page. ([for an example, see pyhocon](https://pypi.python.org/pypi/pyhocon/))

kubernetes-py doesn't seem to have documentation describing this.

If you came up with a list, I would be willing to do the legwork to create a PR for this documentation fix.

**Comment by sebastienc** [comment]
Good comment, I'll add these shortly.

**Comment by sebastienc** [comment]
I've added a few things but there will need to be more work done on documentation.
