### ISSUE TITLE
"kubernetes" is overloaded

### ISSUE THREAD

**Issue by trondhindenes** [mnubo/kubernetes-py#124]
It would probably be better to name the lib `kubernetes_py` or something, `kubernetes` is already the name of the official kubernetes client.

**Comment by eisjcormier** [comment]
+1

**Comment by sebastienc** [comment]
I agree, we're going to rename it.

**Comment by varac** [comment]
Yes please - I have the official "kubernetes" python package installed next to "kubernetes-py".
[powerline-kubernetes](https://github.com/so0k/powerline-kubernetes/blob/master/powerline_kubernetes/segments.py#L3) tries to:

    from kubernetes import K8sConfig

which fails with:

    ImportError: cannot import name K8sConfig


Here in ipython:

```
In [1]: import powerline_kubernetes
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-67be6e01478c> in <module>()
----> 1 import powerline_kubernetes

/usr/local/lib/python2.7/dist-packages/powerline_kubernetes/__init__.py in <module>()
----> 1 from .segments import kubernetes  # noqa

/usr/local/lib/python2.7/dist-packages/powerline_kubernetes/segments.py in <module>()
      1 # vim:fileencoding=utf-8:noet
      2 from powerline.segments import Segment, with_docstring
----> 3 from kubernetes import K8sConfig
      4 
      5 class KubernetesSegment(Segment):

ImportError: cannot import name K8sConfig
```

So renaming soon is much appreciated!

**Comment by sebastienc** [comment]
Hi everyone,

Hopefully this will help you.

Happy holidays.

**Comment by varac** [comment]
@sebastienc Great, thanks!

ftr, this is the new `kubernetes-py` package on pypi.org: https://pypi.org/project/kubernetes-py/
