### ISSUE TITLE
adding user option in the K8sConfig 

### ISSUE THREAD

**Issue by qubusp** [mnubo/kubernetes-py#127]
```cfg_default = K8sConfig(
namespace='xyz',
user='zyx'
)
```
Sometimes it happens that there are multiple users on the same context f. ex. on runners and ci tools

**Comment by sebastienc** [comment]
You can use the parameter auth for this:

:param auth: A tuple of (username, password) for basic authentication.

or use a token instead:

:param token: An authentication token. Mutually exclusive with 'auth'.

But in any case I think a context should have only one user configured for it. You can have multiple contexts but there's only one active context.

https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/
