### ISSUE TITLE
Can PyYAML be unpinned?

### ISSUE THREAD

**Issue by diogobaeder** [mnubo/kubernetes-py#128]
Hi guys,

I just updated my local Python version to 3.7 (which arrived this week in Arch Linux) and I'm migrating a series of packages to it locally, however I also depend on `kubernetes-py` which depends on a pinned version of `PyYAML`, `3.11`, which doesn't seem to work with Python 3.7 (it can't compile here at all).

If you use `3.13` instead, for example, it seems to work just fine (at least I managed to get it running here and doesn't seem to be causing problems). But I think that, as with any library, it's better idea to unpin the dependency, or, at max, establish version ranges if you want to avoid `4.x` for example.

Thanks,
Diogo

**Comment by wmuizelaar** [comment]
+1

**Comment by riconnon** [comment]
I raised PR #131 to update it to 3.13 but I'd also be in favour of unpinning it

**Comment by sebastienc** [comment]
Hi,

Thanks for the comments, it was about time we unpinned it. See: 

https://github.com/mnubo/kubernetes-py/pull/132

**Comment by sebastienc** [comment]
I've released 1.10.0.4.
