### ISSUE TITLE
Support PetSet

### ISSUE THREAD

**Issue by tobegit3hub** [mnubo/kubernetes-py#13]
We want to use Python SDK to access `Kubernetes` to create `PetSet` for cluster applications.

It would be better to see `kubernetes-py` to support `PetSet`.

**Comment by froch** [comment]
Hello! Thank you for the suggestion, and thank you for your interest in our module. PetSets are definitely on our roadmap.

**Comment by sebastienc** [comment]
This is added for the 1.4 series. Closing.

**Comment by tobegit3hub** [comment]
Thanks @froch and @sebastienc 👍
