### ISSUE TITLE
请问如何增加 add_image_pull_secrets

### ISSUE THREAD

**Issue by amoyx** [mnubo/kubernetes-py#139]
使用K8sDeployment时，不知道如何使用 add_image_pull_secrets， 由于拉取docker镜像时需要密钥。但是不知道如何使用add_image_pull_secrets

**Comment by sebastienc** [comment]
Hi,

I'm not sure Google Translate worked correctly, please correct in english if not.

You need to first create the appropriate secrets using K8sSecret. For example:

```
config = K8sConfig(kubeconfig=kubeconfig_fallback)

secret = K8sSecret(config=config,name='my-pull-secret')
data = {"auths": {"repo:port": {"auth": "authstring", "email": "you@company.com"}}}
secret.dockerconfigjson = data
s = secret.create()

deploy = K8sDeployment(config=config, name='my-deployment')
deploy.add_image_pull_secrets(secret={'name': 'my-pull-secret'})
```

Please let me know if this helps.

Regards,

Sebastien

**Comment by amoyx** [comment]
@sebastienc  thks,   perfect

**Comment by amoyx** [comment]
@sebastienc 
![image](https://user-images.githubusercontent.com/19795002/46058101-d0a6b000-c18b-11e8-86ba-b47de7d97d19.png)
