### ISSUE TITLE
Get logs from pods

### ISSUE THREAD

**Issue by soulsplit** [mnubo/kubernetes-py#141]
I noticed that there is no possibility to get logs from pods via a library method. I'm extending the library in my local branch. Would you be interested in a pull request once I'm done?

**Comment by sebastienc** [comment]
Hi, yes I'd be happy to review and merge :) Let me know when you're done!

**Comment by soulsplit** [comment]
Cool! I pushed my changes already. Please see #142 .

**Comment by soulsplit** [comment]
Hi @sebastienc, have you had time to look at the code already?

**Comment by sebastienc** [comment]
Hi, Sorry for the wait. I've accepted your changes and merged the PR. I've published your changes in 1.10.7.2
