### ISSUE TITLE
can you support a kube config file?

### ISSUE THREAD

**Issue by ScubaDrew** [mnubo/kubernetes-py#6]
can you support a kube config file?

**Comment by sebastienc** [comment]
Sure, I'll add it.

**Comment by sebastienc** [comment]
Hi Drew,

Just an FYI, we're currently working on it, should be in there soon.

**Comment by ScubaDrew** [comment]
Much appreciated!

**Comment by sebastienc** [comment]
We need a few more tests before doing a full release but the code in master should be working with kubeconfig files and basic auth. We know we might have issues with certs and tokens for auth.

**Comment by sebastienc** [comment]
We've added that and more functionality in 0.28. You can download it as you please.

**Comment by ScubaDrew** [comment]
Thanks @sebastienc ! Really appreciate it.
